# Generated by Django 4.1.7 on 2023-03-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restifyapp', '0003_alter_property_amen_essential_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='if_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='replythread',
            name='user_response',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
