# Generated by Django 4.1.7 on 2023-03-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restifyapp', '0002_alter_property_amen_essential_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='amen_essential',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='amen_indoor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='amen_outdoor',
            field=models.CharField(max_length=50),
        ),
    ]
