# Generated by Django 4.2 on 2023-04-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restifyapp', '0004_notification_if_read_notification_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replythread',
            name='host_response',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
