# Generated by Django 4.2 on 2023-04-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restifyapp', '0005_alter_replythread_host_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='photos',
            field=models.ImageField(upload_to='property_images'),
        ),
    ]
