# Generated by Django 4.2 on 2023-04-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restifyapp', '0006_alter_property_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='photos',
            field=models.URLField(),
        ),
    ]
