# Generated by Django 4.1.7 on 2023-04-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restifyapp', '0008_alter_property_photos_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestcomment',
            name='host',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertycomment',
            name='guest',
            field=models.PositiveIntegerField(default=4),
            preserve_default=False,
        ),
    ]
